apiVersion: v1
kind: Service

metadata:
  name: gemma-service

spec:

  type: NodePort

  selector:
    job-name: gemma-server

  ports:

    - name: http

      port: 8000

      targetPort: 8000

      nodePort: 30125